package tf

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hashicorp/hcl/v2/hclwrite"
)

// ClusterVariable is one entry from a ClusterClass status.variables, reduced to
// what we need to emit it into a Cluster's topology.
type ClusterVariable struct {
	Name       string
	Scopes     []string // cluster, controlPlane, workers (defaults to cluster)
	Required   bool
	Deprecated bool // description begins with "Deprecated:"
	Schema     *schemaNode
}

// raw shape of a ClusterClass status.variables entry.
type ccVariable struct {
	Name        string         `json:"name"`
	Definitions []ccDefinition `json:"definitions"`
}

type ccDefinition struct {
	From     string `json:"from"`
	Required bool   `json:"required"`
	Schema   struct {
		OpenAPIV3Schema json.RawMessage `json:"openAPIV3Schema"`
	} `json:"schema"`
}

// ParseClusterVariables parses a ClusterClass status.variables JSON array into
// the variable schemas plus their VKS scope annotation.
func ParseClusterVariables(raw []byte) ([]ClusterVariable, error) {
	var list []ccVariable
	if err := json.Unmarshal(raw, &list); err != nil {
		return nil, fmt.Errorf("parse status.variables: %w", err)
	}

	out := make([]ClusterVariable, 0, len(list))
	for _, v := range list {
		def := pickDefinition(v)
		if def == nil {
			continue
		}

		node := &schemaNode{}
		if err := json.Unmarshal(def.Schema.OpenAPIV3Schema, node); err != nil {
			return nil, fmt.Errorf("parse schema for variable %q: %w", v.Name, err)
		}

		out = append(out, ClusterVariable{
			Name:       v.Name,
			Scopes:     scopeOf(def.Schema.OpenAPIV3Schema),
			Required:   def.Required,
			Deprecated: isDeprecated(node.Description),
			Schema:     node,
		})
	}
	return out, nil
}

// pickDefinition prefers the "default" definition, else the first one.
func pickDefinition(v ccVariable) *ccDefinition {
	if len(v.Definitions) == 0 {
		return nil
	}
	for i := range v.Definitions {
		if v.Definitions[i].From == "default" {
			return &v.Definitions[i]
		}
	}
	return &v.Definitions[0]
}

// isDeprecated reports whether a variable's description marks it deprecated.
// VKS signals this only via the description text ("Deprecated: ...").
func isDeprecated(desc string) bool {
	return strings.HasPrefix(strings.ToLower(strings.TrimSpace(desc)), "deprecated")
}

// scopeOf reads the x-vmware-vks/scope annotation. A missing annotation means
// the variable is cluster-global only.
func scopeOf(rawSchema json.RawMessage) []string {
	var probe struct {
		XMeta struct {
			Annotations map[string]string `json:"annotations"`
		} `json:"x-metadata"`
	}
	_ = json.Unmarshal(rawSchema, &probe)

	raw := probe.XMeta.Annotations["x-vmware-vks/scope"]
	if strings.TrimSpace(raw) == "" {
		return []string{"cluster"}
	}
	var scopes []string
	for _, s := range strings.Split(raw, ",") {
		if s = strings.TrimSpace(s); s != "" {
			scopes = append(scopes, s)
		}
	}
	if len(scopes) == 0 {
		return []string{"cluster"}
	}
	return scopes
}

// BuildClusterExample renders a Cluster (kubernetes_manifest) with its topology
// variables expanded from the chosen ClusterClass. Each variable is emitted in
// every section its scope lists:
//
//	cluster      -> spec.topology.variables[]
//	controlPlane -> spec.topology.controlPlane.variables.overrides[]
//	workers      -> spec.topology.workers.machineDeployments[].variables.overrides[]
func BuildClusterExample(group, version, kind, className string, vars []ClusterVariable, opts Options) (string, error) {
	apiVersion := version
	if group != "" {
		apiVersion = group + "/" + version
	}

	var clusterVars, cpVars, workerVars []ClusterVariable
	for _, v := range vars {
		if v.Deprecated {
			continue // skip deprecated variables (e.g. kubeAPIServerFQDNs)
		}
		if opts.RequiredOnly && !v.Required {
			continue // skip optional variables entirely
		}
		for _, s := range v.Scopes {
			switch s {
			case "cluster":
				clusterVars = append(clusterVars, v)
			case "controlPlane":
				cpVars = append(cpVars, v)
			case "workers":
				workerVars = append(workerVars, v)
			}
		}
	}

	g := &generator{set: &schemaSet{schemas: map[string]*schemaNode{}}, sb: &strings.Builder{}, opts: opts}

	g.comment(fmt.Sprintf("VKS Cluster generated by vcf2tf using ClusterClass %q.", className))
	g.comment("Variable schemas come from that ClusterClass's status.variables.")
	g.line(`resource "kubernetes_manifest" "example" {`)
	g.line("manifest = {")
	g.line(fmt.Sprintf("apiVersion = %q", apiVersion))
	g.line(fmt.Sprintf("kind = %q", kind))
	g.metadataBlock()

	g.line("spec = {")
	g.line("topology = {")
	g.comment("The ClusterClass this cluster is built from.")
	g.line(fmt.Sprintf("class = %q", className))
	g.comment("Kubernetes version, e.g. v1.31.1+vmware.1")
	g.line(`version = ""`)

	// control plane
	g.line("controlPlane = {")
	g.comment("Number of control plane nodes.")
	g.line("replicas = 1")
	g.varOverrides(cpVars)
	g.line("}")

	// workers
	g.line("workers = {")
	g.line("machineDeployments = [")
	g.line("{")
	g.comment("Worker pool. 'class' matches a machineDeployment class in the ClusterClass.")
	g.line(`class = ""`)
	g.line(`name  = "md-0"`)
	g.line("replicas = 1")
	g.varOverrides(workerVars)
	g.line("},")
	g.line("]")
	g.line("}")

	// cluster-global variables
	g.comment("Cluster-wide variable values.")
	g.line("variables = [")
	for _, v := range clusterVars {
		g.varEntry(v)
	}
	g.line("]")

	g.line("}") // topology
	g.line("}") // spec
	g.line("}") // manifest
	g.line("}") // resource

	return string(hclwrite.Format([]byte(g.sb.String()))), nil
}

// varOverrides emits a `variables = { overrides = [ ... ] }` block for the
// control plane / worker sections.
func (g *generator) varOverrides(vars []ClusterVariable) {
	g.line("variables = {")
	g.line("overrides = [")
	for _, v := range vars {
		g.varEntry(v)
	}
	g.line("]")
	g.line("}")
}

// varEntry emits one { name = "...", value = <skeleton> } object.
func (g *generator) varEntry(v ClusterVariable) {
	g.line("{")
	g.line(fmt.Sprintf("name = %q", v.Name))
	// reuse the schema walker to build the value skeleton (object style).
	g.field("value", v.Schema, v.Required, 2)
	g.line("},")
}
