package tf

import (
	"fmt"
	"strings"

	"github.com/hashicorp/hcl/v2/hclwrite"
)

// maxDepth bounds recursion so deeply nested (or self-referential) schemas
// produce a usable skeleton instead of an enormous or infinite expansion.
const maxDepth = 6

// BuildExample generates a Terraform skeleton from an OpenAPI v3 document for
// the given group/version/kind. Field placeholders are emitted with the API's
// own descriptions as comments (the data behind `kubectl explain`).
//
// Every kind renders as a kubernetes_manifest with the exact API schema (object
// style, original field names). Options controls how the HCL skeleton is rendered.
type Options struct {
	Comments     bool // emit comments at all
	MarkOptional bool // terse "# optional" markers instead of full descriptions
	RequiredOnly bool // emit only fields the API marks required
	Wait         bool // emit an example wait{} block from the type's status schema
}

func BuildExample(doc []byte, group, version, kind string, opts Options) (string, error) {
	set, err := parseSchemaSet(doc)
	if err != nil {
		return "", err
	}
	root, err := set.findKind(group, version, kind)
	if err != nil {
		return "", err
	}

	apiVersion := version
	if group != "" {
		apiVersion = group + "/" + version
	}

	g := &generator{set: set, sb: &strings.Builder{}, opts: opts}
	g.manifest(kind, apiVersion, root)

	// Canonicalize indentation/spacing; equivalent to `terraform fmt`.
	formatted := hclwrite.Format([]byte(g.sb.String()))
	return string(formatted), nil
}

type generator struct {
	set  *schemaSet
	sb   *strings.Builder
	opts Options
}

func (g *generator) line(s string) { g.sb.WriteString(s + "\n") }

// comment emits a structural/header comment (not a per-field doc). Shown
// whenever comments are enabled, regardless of MarkOptional.
func (g *generator) comment(text string) {
	if !g.opts.Comments {
		return
	}
	for _, l := range wrapComment(text) {
		g.line("# " + l)
	}
}

// note emits a per-field annotation. In MarkOptional mode optional fields get a
// terse "# optional" and required fields get nothing; otherwise the full text.
func (g *generator) note(required bool, full string) {
	if !g.opts.Comments {
		return
	}
	if g.opts.MarkOptional {
		if !required {
			g.line("# optional")
		}
		return
	}
	if full != "" {
		g.comment(full)
	}
}

// manifest renders a kubernetes_manifest resource (object-literal style).
func (g *generator) manifest(kind, apiVersion string, root *schemaNode) {
	g.comment("Skeleton generated by vcf2tf from the cluster's OpenAPI schema.")
	g.line("resource \"kubernetes_manifest\" \"example\" {")
	g.line("manifest = {")
	g.line(fmt.Sprintf("apiVersion = %q", apiVersion))
	g.line(fmt.Sprintf("kind = %q", kind))

	g.metadataBlock()

	for _, key := range sortedKeys(toIfaceMap(root.Properties)) {
		switch key {
		case "apiVersion", "kind", "status", "metadata":
			continue
		}
		g.field(key, root.Properties[key], topRequired(root, key), 2)
	}
	g.line("}") // manifest

	if g.opts.Wait {
		g.waitBlock(kind, root)
	}

	g.line("}") // resource
}

// topRequired keeps the structural `spec` root even when the object's schema
// does not list it as required, so required-only output isn't empty. Filtering
// still applies to spec's descendants.
func topRequired(root *schemaNode, key string) bool {
	return key == "spec" || isRequired(root, key)
}

// metadataBlock emits a slim, commented metadata section rather than expanding
// the full (huge) ObjectMeta schema. In required-only mode just `name` is kept.
func (g *generator) metadataBlock() {
	g.comment("Standard object metadata.")
	g.line("metadata = {")
	g.note(true, "Name of the object (required).")
	g.line(`name = ""`)
	if !g.opts.RequiredOnly {
		g.note(false, "Namespace to create the object in.")
		g.line(`namespace = ""`)
		g.note(false, "Key/value labels.")
		g.line("labels = {}")
		g.note(false, "Key/value annotations.")
		g.line("annotations = {}")
	}
	g.line("}")
}

// field renders one property as an object-literal attribute.
func (g *generator) field(name string, node *schemaNode, required bool, depth int) {
	if g.opts.RequiredOnly && !required {
		return
	}
	resolved, desc := g.set.resolve(node)
	if resolved == nil {
		return
	}

	g.emitDoc(desc, resolved, required)

	if depth >= maxDepth && !resolved.isScalar() {
		g.comment("(nested fields omitted: max depth reached)")
		g.line(attr(name) + "{}")
		return
	}

	switch {
	case resolved.isMap():
		g.line(attr(name) + "{}")

	case resolved.Type == "object" && len(resolved.Properties) > 0:
		g.openContainer(name)
		g.writeProperties(resolved, depth+1)
		g.line("}")

	case resolved.Type == "array":
		g.array(name, resolved, depth)

	default:
		g.line(attr(name) + scalarPlaceholder(resolved))
	}
}

func (g *generator) array(name string, node *schemaNode, depth int) {
	items, _ := g.set.resolve(node.Items)
	if items != nil && items.Type == "object" && len(items.Properties) > 0 {
		g.line(name + " = [")
		g.line("{")
		g.writeProperties(items, depth+1)
		g.line("}")
		g.line("]")
		return
	}
	// array of scalars
	g.line(attr(name) + "[]")
}

func (g *generator) writeProperties(node *schemaNode, depth int) {
	for _, key := range sortedKeys(toIfaceMap(node.Properties)) {
		g.field(key, node.Properties[key], isRequired(node, key), depth)
	}
}

func (g *generator) openContainer(name string) {
	g.line(name + " = {")
}

// emitDoc writes the description plus a required/type/enum annotation line.
// In MarkOptional mode it collapses to a terse "# optional" on optional fields.
func (g *generator) emitDoc(desc string, node *schemaNode, required bool) {
	if !g.opts.Comments {
		return
	}
	if g.opts.MarkOptional {
		if !required {
			g.line("# optional")
		}
		return
	}
	if desc != "" {
		g.comment(desc)
	}
	var ann []string
	if required {
		ann = append(ann, "required")
	}
	if t := node.typeLabel(); t != "" {
		ann = append(ann, t)
	}
	if len(node.Enum) > 0 {
		ann = append(ann, "one of: "+enumList(node.Enum))
	}
	if len(ann) > 0 {
		g.line("# [" + strings.Join(ann, ", ") + "]")
	}
}
