package tf

import (
	"fmt"
	"strings"

	"github.com/hashicorp/hcl/v2/hclwrite"
)

// maxDepth bounds recursion so deeply nested (or self-referential) schemas
// produce a usable skeleton instead of an enormous or infinite expansion.
const maxDepth = 6

// BuildExample generates a Terraform skeleton from an OpenAPI v3 document for
// the given group/version/kind. Field placeholders are emitted with the API's
// own descriptions as comments (the data behind `kubectl explain`).
//
// Native core/apps/batch/... kinds render as their native kubernetes_* provider
// resource (block style, snake_case). Everything else renders as a
// kubernetes_manifest with the exact API schema (object style, original names).
func BuildExample(doc []byte, group, version, kind string) (string, error) {
	set, err := parseSchemaSet(doc)
	if err != nil {
		return "", err
	}
	root, err := set.findKind(group, version, kind)
	if err != nil {
		return "", err
	}

	apiVersion := version
	if group != "" {
		apiVersion = group + "/" + version
	}

	g := &generator{set: set, sb: &strings.Builder{}}

	if tfType, ok := nativeType(gvk(group, version, kind)); ok {
		g.native(tfType, kind, apiVersion, root)
	} else {
		g.manifest(kind, apiVersion, root)
	}

	// Canonicalize indentation/spacing; equivalent to `terraform fmt`.
	formatted := hclwrite.Format([]byte(g.sb.String()))
	return string(formatted), nil
}

type generator struct {
	set *schemaSet
	sb  *strings.Builder
}

func (g *generator) line(s string) { g.sb.WriteString(s + "\n") }
func (g *generator) comment(text string) {
	for _, l := range wrapComment(text) {
		g.line("# " + l)
	}
}

// native renders a native kubernetes_* provider resource (block style).
func (g *generator) native(tfType, kind, apiVersion string, root *schemaNode) {
	g.comment(fmt.Sprintf("Native mapping of %s/%s -> %s.", apiVersion, kind, tfType))
	g.comment("Skeleton generated by vcf2tf from the cluster's OpenAPI schema.")
	g.line(fmt.Sprintf("resource %q \"example\" {", tfType))

	g.metadataBlock(false)

	for _, key := range sortedKeys(toIfaceMap(root.Properties)) {
		switch key {
		case "apiVersion", "kind", "status", "metadata":
			continue
		}
		g.field(key, root.Properties[key], false, isRequired(root, key), 1)
	}
	g.line("}")
}

// manifest renders a kubernetes_manifest resource (object-literal style).
func (g *generator) manifest(kind, apiVersion string, root *schemaNode) {
	g.comment("Custom resource with no native provider mapping; managed via kubernetes_manifest.")
	g.comment("Skeleton generated by vcf2tf from the cluster's OpenAPI schema.")
	g.line("resource \"kubernetes_manifest\" \"example\" {")
	g.line("manifest = {")
	g.line(fmt.Sprintf("apiVersion = %q", apiVersion))
	g.line(fmt.Sprintf("kind = %q", kind))

	g.metadataBlock(true)

	for _, key := range sortedKeys(toIfaceMap(root.Properties)) {
		switch key {
		case "apiVersion", "kind", "status", "metadata":
			continue
		}
		g.field(key, root.Properties[key], true, isRequired(root, key), 2)
	}
	g.line("}") // manifest
	g.line("}") // resource
}

// metadataBlock emits a slim, commented metadata section rather than expanding
// the full (huge) ObjectMeta schema.
func (g *generator) metadataBlock(object bool) {
	open := "metadata {"
	if object {
		open = "metadata = {"
	}
	g.comment("Standard object metadata.")
	g.line(open)
	g.comment("Name of the object (required).")
	g.line(`name = ""`)
	g.comment("Namespace to create the object in.")
	g.line(`namespace = ""`)
	g.comment("Key/value labels.")
	g.line("labels = {}")
	g.comment("Key/value annotations.")
	g.line("annotations = {}")
	g.line("}")
}

// field renders one property. object selects object-literal vs block style.
func (g *generator) field(rawName string, node *schemaNode, object, required bool, depth int) {
	resolved, desc := g.set.resolve(node)
	if resolved == nil {
		return
	}

	name := rawName
	if !object {
		name = camelToSnake(rawName)
	}

	g.emitDoc(desc, resolved, required)

	if depth >= maxDepth && !resolved.isScalar() {
		g.comment("(nested fields omitted: max depth reached)")
		g.line(attr(name) + "{}")
		return
	}

	switch {
	case resolved.isMap():
		g.line(attr(name) + "{}")

	case resolved.Type == "object" && len(resolved.Properties) > 0:
		g.openContainer(name, object, "{")
		g.writeProperties(resolved, object, depth+1)
		g.line("}")

	case resolved.Type == "array":
		g.array(name, resolved, object, depth)

	default:
		g.line(attr(name) + scalarPlaceholder(resolved))
	}
}

func (g *generator) array(name string, node *schemaNode, object bool, depth int) {
	items, _ := g.set.resolve(node.Items)
	if items != nil && items.Type == "object" && len(items.Properties) > 0 {
		if object {
			g.line(name + " = [")
			g.line("{")
			g.writeProperties(items, true, depth+1)
			g.line("}")
			g.line("]")
		} else {
			// native: repeated block, singularized.
			g.line(singularize(name) + " {")
			g.writeProperties(items, false, depth+1)
			g.line("}")
		}
		return
	}
	// array of scalars
	g.line(attr(name) + "[]")
}

func (g *generator) writeProperties(node *schemaNode, object bool, depth int) {
	for _, key := range sortedKeys(toIfaceMap(node.Properties)) {
		g.field(key, node.Properties[key], object, isRequired(node, key), depth)
	}
}

func (g *generator) openContainer(name string, object bool, brace string) {
	if object {
		g.line(name + " = " + brace)
	} else {
		g.line(name + " " + brace)
	}
}

// emitDoc writes the description plus a required/type/enum annotation line.
func (g *generator) emitDoc(desc string, node *schemaNode, required bool) {
	if desc != "" {
		g.comment(desc)
	}
	var ann []string
	if required {
		ann = append(ann, "required")
	}
	if t := node.typeLabel(); t != "" {
		ann = append(ann, t)
	}
	if len(node.Enum) > 0 {
		ann = append(ann, "one of: "+enumList(node.Enum))
	}
	if len(ann) > 0 {
		g.line("# [" + strings.Join(ann, ", ") + "]")
	}
}
